// <auto-generated />
using System;
using GymForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymForge.Infrastructure.Migrations
{
    [DbContext(typeof(GymForgeDbContext))]
    partial class GymForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GymForge.Domain.Entities.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AccessGranted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DoorId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SwipedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagSerial")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagSerial")
                        .HasDatabaseName("IX_AccessLogs_TagSerial");

                    b.HasIndex("DoorId", "SwipedAt")
                        .HasDatabaseName("IX_AccessLogs_DoorSwipedAt");

                    b.HasIndex("MemberId", "SwipedAt")
                        .HasDatabaseName("IX_AccessLogs_MemberSwipedAt");

                    b.HasIndex("SiteId", "SwipedAt")
                        .HasDatabaseName("IX_AccessLogs_SiteSwipedAt");

                    b.ToTable("AccessLogs", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiffJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_CompanyTimestamp");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.BodyMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AbdomenCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AbdominalMm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BasalMetabolicRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyFatMethod")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BodyFatPct")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal?>("BodyWaterPct")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChestCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChestMm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<decimal?>("HipsCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LeftBicepCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LeftCalfCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LeftForearmCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LeftThighCm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MuscleMassKg")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<decimal?>("NeckCm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoBack")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoFront")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoSide")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RightBicepCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RightCalfCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RightForearmCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RightThighCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ShouldersCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SubscapularMm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuprailiacMm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TakenByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ThighMm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TricepsMm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisceralFat")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WaistCm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("DECIMAL(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "MeasuredAt")
                        .HasDatabaseName("IX_BodyMeasurements_MemberDate");

                    b.ToTable("BodyMeasurements", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentChargeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaitlistPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassScheduleId", "Status")
                        .HasDatabaseName("IX_Bookings_ScheduleStatus");

                    b.HasIndex("MemberId", "Status")
                        .HasDatabaseName("IX_Bookings_MemberStatus");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.CashMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("IX_CashMovements_Shift");

                    b.ToTable("CashMovements", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConceptType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalCae")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalXmlUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("MemberId", "Status")
                        .HasDatabaseName("IX_Charges_MemberStatus");

                    b.HasIndex("CompanyId", "DueDate", "Status")
                        .HasDatabaseName("IX_Charges_DueDateStatus");

                    b.ToTable("Charges", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.ClassDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultDurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentNeeded")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_ClassDescriptions_Company");

                    b.ToTable("ClassDescriptions", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookingCloseBeforeMin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BookingOpenFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("CancelDeadlineMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClassDescriptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DropInPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDatetime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LateCancelFee")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NoShowFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitlistCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassDescriptionId");

                    b.HasIndex("InstructorId", "StartDatetime")
                        .HasDatabaseName("IX_ClassSchedules_InstructorStart");

                    b.HasIndex("SiteId", "StartDatetime")
                        .HasDatabaseName("IX_ClassSchedules_SiteStart");

                    b.ToTable("ClassSchedules", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandColorHex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("IX_Companies_TaxId");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimatedGifUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTimed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnilateral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMuscleGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMuscleGroupsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryMuscleGroup")
                        .HasDatabaseName("IX_Exercises_MuscleGroup");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Exercises_Tenant");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyRelation")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FingerprintTemplate")
                        .HasColumnType("BLOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParQId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferredByMemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SalesRepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagSerial")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WaiverSignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .HasDatabaseName("IX_Members_Document");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Members_Email");

                    b.HasIndex("SiteId");

                    b.HasIndex("TagSerial")
                        .HasDatabaseName("IX_Members_TagSerial");

                    b.HasIndex("CompanyId", "SiteId", "Status")
                        .HasDatabaseName("IX_Members_CompanySiteStatus");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractPdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FreezeCountUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FreezeEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("FreezeReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FreezeStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembershipTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextBillingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SoldByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisitsRemaining")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeId");

                    b.HasIndex("CompanyId", "EndDate")
                        .HasDatabaseName("IX_Memberships_CompanyEndDate");

                    b.HasIndex("MemberId", "Status")
                        .HasDatabaseName("IX_Memberships_MemberStatus");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.MembershipType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AgeMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedClassTypesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDoorIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BenefitIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClassCreditsIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenderRestriction")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("PtSessionsIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleRestrictionJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SignupFee")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsActive")
                        .HasDatabaseName("IX_MembershipTypes_CompanyActive");

                    b.ToTable("MembershipTypes", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorTxId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_Payments_Member");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("IX_Payments_Shift");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId")
                        .HasDatabaseName("IX_Allocations_Charge");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_Allocations_Payment");

                    b.ToTable("PaymentAllocations", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionStaffPct")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSellableOnline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("IX_Products_Barcode");

                    b.HasIndex("CompanyId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_CompanySku");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_Routines_Member");

                    b.ToTable("Routines", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineDays", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoutineDayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tempo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RoutineDayId");

                    b.ToTable("RoutineItems", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineItemSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoutineItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetDurationSec")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepsMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRpe")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoutineItemId");

                    b.ToTable("RoutineItemSets", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("FiscalCae")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalXmlUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDatetime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_Sales_Member");

                    b.HasIndex("SiteId", "SaleDatetime")
                        .HasDatabaseName("IX_Sales_SiteDate");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommissionStaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<Guid?>("MembershipTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(12,3)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleLines", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ClosingCashDeclared")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal?>("ClosingCashSystem")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningCash")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Status")
                        .HasDatabaseName("IX_Shifts_SiteStatus");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandColorHex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GeoLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("GeoLng")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ManagerStaffId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenHoursJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Sites_Company");

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionPctMemberships")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("CommissionPctProducts")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("CommissionPctPt")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinCodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialtiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Staff_Email");

                    b.HasIndex("CompanyId", "Role")
                        .HasDatabaseName("IX_Staff_CompanyRole");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.StockBySite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Qty")
                        .HasColumnType("DECIMAL(12,3)");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("DECIMAL(12,3)");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockBySite_ProductSite");

                    b.ToTable("StockBySite", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualDurationSecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualRepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualSetsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualWeightKgJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoutineItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rpe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "PerformedAt")
                        .HasDatabaseName("IX_WorkoutLogs_MemberPerformedAt");

                    b.ToTable("WorkoutLogs", (string)null);
                });

            modelBuilder.Entity("GymForge.Domain.Entities.AccessLog", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany("AccessLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Booking", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.ClassSchedule", "ClassSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSchedule");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.CashMovement", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Shift", "Shift")
                        .WithMany("Movements")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Charge", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany("Charges")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymForge.Domain.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.ClassSchedule", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.ClassDescription", "ClassDescription")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassDescription");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Member", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Site", "Site")
                        .WithMany("Members")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Membership", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymForge.Domain.Entities.MembershipType", "MembershipType")
                        .WithMany()
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Payment", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Charge", "Charge")
                        .WithMany("Allocations")
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymForge.Domain.Entities.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charge");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Routine", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineDay", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Routine", "Routine")
                        .WithMany("Days")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineItem", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymForge.Domain.Entities.RoutineDay", "RoutineDay")
                        .WithMany("Items")
                        .HasForeignKey("RoutineDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("RoutineDay");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineItemSet", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.RoutineItem", "RoutineItem")
                        .WithMany("Sets")
                        .HasForeignKey("RoutineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoutineItem");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.SaleLine", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Sale", "Sale")
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Site", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Company", "Company")
                        .WithMany("Sites")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Staff", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Company", "Company")
                        .WithMany("Staff")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.StockBySite", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Product", "Product")
                        .WithMany("Stock")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("GymForge.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Charge", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.ClassDescription", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.ClassSchedule", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Company", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Member", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("Charges");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Product", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Routine", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineDay", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.RoutineItem", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Shift", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("GymForge.Domain.Entities.Site", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
