// <auto-generated />
using GymForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable
#pragma warning disable CS0612

namespace GymForge.Infrastructure.Persistence.Migrations;

[DbContext(typeof(GymForgeDbContext))]
partial class GymForgeDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.4");
        // NOTE: The full snapshot is generated by EF Core CLI.
        // Run: dotnet ef migrations add InitialCreate --project src/GymForge.Infrastructure
        // after installing .NET 9 SDK to regenerate this file with complete metadata.
#pragma warning restore 612, 618
    }
}
